In [1]:
# Import pandas
import pandas as pd

In [2]:
# Load the original dataset
file_path = "../data/raw/dataset-tickets-multi-lang-4-20k.csv"

df = pd.read_csv(file_path)

print("Original shape:", df.shape)

Original shape: (20000, 15)

In [3]:
# Keep only columns needed for prompt experiments
columns_to_keep = [
    "subject",
    "body",
    "answer",
    "type",
    "queue",
    "priority",
    "language"
]

df_clean = df[columns_to_keep].copy()

df_clean.head()

,subject,body,answer,type,queue,priority,language
0,Unvorhergesehener Absturz der Datenanalyse-Pla...,Die Datenanalyse-Plattform brach unerwartet ab...,Ich werde Ihnen bei der Lösung des Problems he...,Incident,General Inquiry,low,de
1,Customer Support Inquiry,Seeking information on digital strategies that...,We offer a variety of digital strategies and s...,Request,Customer Service,medium,en
2,Data Analytics for Investment,I am contacting you to request information on ...,I am here to assist you with data analytics to...,Request,Customer Service,medium,en
3,Krankenhaus-Dienstleistung-Problem,Ein Medien-Daten-Sperrverhalten trat aufgrund ...,Zurück zur E-Mail-Beschwerde über den Sperrver...,Incident,Customer Service,high,de
4,Security,"Dear Customer Support, I am reaching out to in...","Dear [name], we take the security of medical d...",Request,Customer Service,medium,en

In [4]:
# Keep only columns needed for prompt experiments
columns_to_keep = [
    "subject",
    "body",
    "answer",
    "type",
    "queue",
    "priority",
    "language"
]

df_clean = df[columns_to_keep].copy()

df_clean.head()

,subject,body,answer,type,queue,priority,language
0,Unvorhergesehener Absturz der Datenanalyse-Pla...,Die Datenanalyse-Plattform brach unerwartet ab...,Ich werde Ihnen bei der Lösung des Problems he...,Incident,General Inquiry,low,de
1,Customer Support Inquiry,Seeking information on digital strategies that...,We offer a variety of digital strategies and s...,Request,Customer Service,medium,en
2,Data Analytics for Investment,I am contacting you to request information on ...,I am here to assist you with data analytics to...,Request,Customer Service,medium,en
3,Krankenhaus-Dienstleistung-Problem,Ein Medien-Daten-Sperrverhalten trat aufgrund ...,Zurück zur E-Mail-Beschwerde über den Sperrver...,Incident,Customer Service,high,de
4,Security,"Dear Customer Support, I am reaching out to in...","Dear [name], we take the security of medical d...",Request,Customer Service,medium,en

In [5]:
# Keep only English customer support tickets
df_clean = df_clean[df_clean["language"] == "en"].copy()

print("English tickets:", len(df_clean))

English tickets: 11923

In [6]:
# Check missing values after filtering
df_clean.isnull().sum()

subject     1032
body           1
answer         3
type           0
queue          0
priority       0
language       0
dtype: int64

In [7]:
# Fill missing subjects with a placeholder
df_clean["subject"] = df_clean["subject"].fillna("No subject")

# Remove rows missing important text fields
df_clean = df_clean.dropna(subset=["body", "answer"])

print("Rows after handling missing values:", len(df_clean))

Rows after handling missing values: 11919

In [8]:
# Remove unnecessary leading and trailing spaces
text_columns = ["subject", "body", "answer"]

for col in text_columns:
    df_clean[col] = df_clean[col].str.strip()

In [9]:
# Clean whitespace in label columns
category_columns = ["type", "queue", "priority", "language"]

for col in category_columns:
    df_clean[col] = df_clean[col].str.strip()

In [10]:
# Remove duplicate records if any exist
before = len(df_clean)

df_clean = df_clean.drop_duplicates()

after = len(df_clean)

print("Duplicates removed:", before - after)

Duplicates removed: 0

In [11]:
# Reset row index after cleaning
df_clean = df_clean.reset_index(drop=True)

df_clean.head()

,subject,body,answer,type,queue,priority,language
0,Customer Support Inquiry,Seeking information on digital strategies that...,We offer a variety of digital strategies and s...,Request,Customer Service,medium,en
1,Data Analytics for Investment,I am contacting you to request information on ...,I am here to assist you with data analytics to...,Request,Customer Service,medium,en
2,Security,"Dear Customer Support, I am reaching out to in...","Dear [name], we take the security of medical d...",Request,Customer Service,medium,en
3,Concerns About Securing Medical Data on 2-in-1...,Inquiring about best practices for securing me...,Thank you for your concern regarding securing ...,Request,Technical Support,medium,en
4,Problem with Integration,"The integration stopped working unexpectedly, ...",I will look into the problem and call you at <...,Problem,IT Support,high,en

In [12]:
# Display final dataset information
print("Final shape:", df_clean.shape)

print("\nMissing values:")
print(df_clean.isnull().sum())

print("\nLanguages:")
print(df_clean["language"].value_counts())

Final shape: (11919, 7)

Missing values:
subject     0
body        0
answer      0
type        0
queue       0
priority    0
language    0
dtype: int64

Languages:
language
en    11919
Name: count, dtype: int64

In [13]:
# Check labels used later for classification
print("Ticket Types:")
print(df_clean["type"].value_counts())

print("\nPriorities:")
print(df_clean["priority"].value_counts())

print("\nQueues:")
print(df_clean["queue"].value_counts())

Ticket Types:
type
Incident    4642
Request     3498
Problem     2494
Change      1285
Name: count, dtype: int64

Priorities:
priority
medium    4949
high      4570
low       2400
Name: count, dtype: int64

Queues:
queue
Technical Support                  3411
Product Support                    2230
Customer Service                   1859
IT Support                         1391
Billing and Payments               1301
Returns and Exchanges               582
Service Outages and Maintenance     442
Sales and Pre-Sales                 330
Human Resources                     205
General Inquiry                     168
Name: count, dtype: int64

In [14]:
# Save the cleaned dataset
output_path = "../data/processed/cleaned_customer_support_tickets.csv"

df_clean.to_csv(output_path, index=False)

print("Cleaned dataset saved successfully.")

Cleaned dataset saved successfully.

In [15]:
# Reload saved dataset to verify the file
check_df = pd.read_csv(
    "../data/processed/cleaned_customer_support_tickets.csv"
)

print(check_df.shape)
check_df.head()

(11919, 7)

,subject,body,answer,type,queue,priority,language
0,Customer Support Inquiry,Seeking information on digital strategies that...,We offer a variety of digital strategies and s...,Request,Customer Service,medium,en
1,Data Analytics for Investment,I am contacting you to request information on ...,I am here to assist you with data analytics to...,Request,Customer Service,medium,en
2,Security,"Dear Customer Support, I am reaching out to in...","Dear [name], we take the security of medical d...",Request,Customer Service,medium,en
3,Concerns About Securing Medical Data on 2-in-1...,Inquiring about best practices for securing me...,Thank you for your concern regarding securing ...,Request,Technical Support,medium,en
4,Problem with Integration,"The integration stopped working unexpectedly, ...",I will look into the problem and call you at <...,Problem,IT Support,high,en

In [16]:
# Load the cleaned customer support dataset
clean_df = pd.read_csv(
    "../data/processed/cleaned_customer_support_tickets.csv"
)

clean_df.shape

(11919, 7)

In [17]:
# Sample 30 tickets from each ticket type
experiment_df = (
    clean_df
    .groupby("type", group_keys=False)
    .apply(lambda x: x.sample(n=30, random_state=42))
    .reset_index(drop=True)
)

print("Experiment dataset shape:", experiment_df.shape)

Experiment dataset shape: (120, 6)

In [18]:
# Create a balanced sample of 30 tickets from each ticket type
experiment_df = (
    clean_df
    .groupby("type", group_keys=False)
    .sample(n=30, random_state=42)
    .reset_index(drop=True)
)

print("Experiment dataset shape:", experiment_df.shape)

Experiment dataset shape: (120, 7)

In [19]:
# Verify ticket type distribution
experiment_df["type"].value_counts()

type
Change      30
Incident    30
Problem     30
Request     30
Name: count, dtype: int64

In [20]:
# Inspect priority distribution in the sample
experiment_df["priority"].value_counts()

priority
medium    51
high      40
low       29
Name: count, dtype: int64

In [21]:
# Add a unique experiment ID
experiment_df.insert(
    0,
    "ticket_id",
    range(1, len(experiment_df) + 1)
)

experiment_df.head()

,ticket_id,subject,body,answer,type,queue,priority,language
0,1,Product Support Inquiry,Requesting an update on the product's compatib...,"Dear <name>, thank you for reaching out to us ...",Change,Returns and Exchanges,medium,en
1,2,Support for Webcam,I would like to inquire about the possibility ...,We will evaluate the feasibility of adding web...,Change,General Inquiry,low,en
2,3,Support Request for Billing Details Update,I am writing to request an update to my billin...,We will assist you in updating your billing de...,Change,Billing and Payments,high,en
3,4,Request for Updating Analytics Tools,"Customer Support, requesting an update to the ...",Received your request to update the analytics ...,Change,Service Outages and Maintenance,low,en
4,5,Modify Employee Training Curriculum for Data A...,I am contacting you to suggest updating the em...,"Dear <name>, we thank you for proposing to upd...",Change,Human Resources,medium,en

In [22]:
# Shuffle rows so ticket types are mixed
experiment_df = experiment_df.sample(
    frac=1,
    random_state=42
).reset_index(drop=True)

In [23]:
# Recreate sequential ticket IDs after shuffling
experiment_df["ticket_id"] = range(1, len(experiment_df) + 1)

In [24]:
# Preview selected experiment records
experiment_df.head(10)

,ticket_id,subject,body,answer,type,queue,priority,language
0,1,Problem with Server During Peak Hours,"To Whom It May Concern, I hope this message fi...","Dear [Customer Name], Thank you for your email...",Incident,Service Outages and Maintenance,medium,en
1,2,Concern Regarding Data Security Breach,Data security breaches have affected the hospi...,Immediate investigation into the data security...,Incident,Technical Support,low,en
2,3,Modify Employee Training Curriculum for Data A...,I am contacting you to suggest updating the em...,"Dear <name>, we thank you for proposing to upd...",Change,Human Resources,medium,en
3,4,Project Management Portal Freezing Issues,The project management portal has frozen unexp...,I will look into the project management portal...,Incident,Customer Service,medium,en
4,5,No subject,"Dear Customer Support, I am writing to request...",Thank you for reaching out to us to enhance yo...,Change,Technical Support,high,en
5,6,Unanticipated Medical Information Leak Was Noted,Incident details: An unforeseen medical inform...,I plan to delve into the medical information l...,Problem,Technical Support,high,en
6,7,Problem with Inconsistency in Digital Campaign...,The campaign metrics are not aligning properly...,I have noted your concerns about the digital c...,Problem,IT Support,low,en
7,8,Security Enhancement for Medical Data,To Customer Support: I am contacting you to as...,"Hello <name>, thank you for contacting us to i...",Change,Product Support,low,en
8,9,Address Security Concern Detected,An unauthorized access attempt has been identi...,We take this security concern very seriously a...,Incident,Product Support,low,en
9,10,No subject,"Dear Customer Support, I am inquiring about op...","<name>, thank you for your inquiry regarding t...",Request,Billing and Payments,high,en

In [25]:
# Save the balanced dataset used for prompt experiments
experiment_path = "../data/processed/prompt_experiment_tickets.csv"

experiment_df.to_csv(
    experiment_path,
    index=False
)

print("Prompt experiment dataset saved successfully.")

Prompt experiment dataset saved successfully.

In [26]:
# Verify the saved experiment dataset
test_df = pd.read_csv(
    "../data/processed/prompt_experiment_tickets.csv"
)

print("Shape:", test_df.shape)

print("\nTicket type distribution:")
print(test_df["type"].value_counts())

test_df.head()

Shape: (120, 8)

Ticket type distribution:
type
Incident    30
Change      30
Problem     30
Request     30
Name: count, dtype: int64

,ticket_id,subject,body,answer,type,queue,priority,language
0,1,Problem with Server During Peak Hours,"To Whom It May Concern, I hope this message fi...","Dear [Customer Name], Thank you for your email...",Incident,Service Outages and Maintenance,medium,en
1,2,Concern Regarding Data Security Breach,Data security breaches have affected the hospi...,Immediate investigation into the data security...,Incident,Technical Support,low,en
2,3,Modify Employee Training Curriculum for Data A...,I am contacting you to suggest updating the em...,"Dear <name>, we thank you for proposing to upd...",Change,Human Resources,medium,en
3,4,Project Management Portal Freezing Issues,The project management portal has frozen unexp...,I will look into the project management portal...,Incident,Customer Service,medium,en
4,5,No subject,"Dear Customer Support, I am writing to request...",Thank you for reaching out to us to enhance yo...,Change,Technical Support,high,en